# --- Conversation States ---
(
    SELECTING_ACTION,
    AWAITING_METRIC_CHOICE,
    AWAIT_MEAL_INPUT,
    AWAIT_MEAL_CONFIRMATION,
    AWAIT_METRIC_INPUT,
    ASK_LOG_MORE,
    AWAIT_MACRO_EDIT,
    AWAIT_ITEM_QUANTITY_EDIT,
) = range(8)

# Export states for use in main handler definition
CONVERSATION_STATES = {
    SELECTING_ACTION,
    AWAITING_METRIC_CHOICE,
    AWAIT_MEAL_INPUT,
    AWAIT_MEAL_CONFIRMATION,
    AWAIT_METRIC_INPUT,
    ASK_LOG_MORE,
    AWAIT_MACRO_EDIT,
    AWAIT_ITEM_QUANTITY_EDIT,
} 